### PR TITLE
fix: Par2 repairing status

### PR DESCRIPTION
**Pull request by dnzbk**
## Description

[issue](https://github.com/nzbgetcom/nzbget/pull/420#issuecomment-2476408211)
- fixed Par2 repair status showing in the webui

## Testing

- Windows 11

### CODE REVIEW

**Review by luckedea — APPROVED** [review]

**Comment by isarrider** [comment]
Does not fix it for me - still just a dark bar while repairing...

**Comment by isarrider** [comment]
hmm interesting...
I tried with a couple of nzbs and it doenst make a difference...
it is fast as hell but doesnt throw infos...
Give me some time to think about it...

**Comment by isarrider** [comment]
Actually now it works - weird...
But I don't get a time remaining info when it downloads the par files needed to repair...

**Comment by dnzbk** [comment]
Yes, the information about the remaining Par2 file download time is incorrect but this bug is not caused by the recent changes and has existed since at least v21.1. I’ll look into it when I have some free time.

**Comment by dnzbk** [comment]
@isarrider
Transformed to the [issue](https://github.com/nzbgetcom/nzbget/issues/473)

**Pull request merged**
